### ISSUE TITLE
can not test drive

### ISSUE THREAD

**Issue by yumaihiko** [deviljin112/daily_CarTestDrive#3]
SCRIPT ERROR: @es_extended/server/classes/player.lua:299: attempt to index a nil value (local 'account')
> ref (@es_extended/server/classes/player.lua:299)
> ref (@daily_CarTestDrive/server/main.lua:23)
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:88)

**Comment by deviljin112** [comment]
This isnt an issue on 1.2 / 1.final. The script is not finished, and if you are using an old db system without "accounts" this script will not work and you will have to edit it to your version.
